name: Build YTExt -> dmg

on:
  push:
    branches:
      - '**'

jobs:
  build-macos-app:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for Gradle Build Scan

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'  # Cache Gradle dependencies

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: gradle-cache-key-${{ github.sha }}
          
      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build macOS App
        env:
          GOOGLE_AI_STUDIO_API_KEY: ${{ secrets.GOOGLE_AI_STUDIO_API_KEY }}
          YT_APP_NAME: ${{ secrets.YT_APP_NAME }}
          YT_DATA_API_V3_KEY: ${{ secrets.YT_DATA_API_V3_KEY }}
        run: |
          ./gradlew packageDmg -PreleaseBuild=true --build-cache --configuration-cache --parallel

      - name: Get current timestamp
        id: date
        run: echo "date=$(date -u +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Upload macOS .dmg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ytext-${{ github.ref_name }}-${{ steps.date.outputs.date }}.dmg
          path: composeApp/build/compose/binaries/main/dmg/*.dmg
          retention-days: 1