name: Build YTExt -> dmg

on:
  push:
    branches:
      - '**'

jobs:
  build-macos-app:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build macOS App
        run: ./gradlew packageDmg -PreleaseBuild=true

      - name: Get current timestamp
        id: date
        run: echo "date=$(date -u +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Upload macOS .dmg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ytext-${{ github.ref_name }}-${{ steps.date.outputs.date }}.dmg
          path: composeApp/build/compose/binaries/main/dmg/*.dmg
          retention-days: 1